# Keras
# for amd64
# 20171104
 
FROM tensorflow/tensorflow:latest-gpu-py3

MAINTAINER Wei Lin

# USER root

# Add user pi
# RUN \
# 	useradd -G adm,sudo,users -s /bin/bash -m pi && \
# 	echo 'pi:raspberry' | chpasswd


RUN pip3 install keras

