# by: Wei Lin
# date: 2017/2/18  

FROM wei1234c/esp8266_armv7

MAINTAINER Wei Lin

ENV TERM linux

WORKDIR /home/xtensa
RUN git clone --recursive https://github.com/micropython/micropython.git 
WORKDIR /home/xtensa/micropython