docker rmi oracle-java8
docker rmi sshd
docker rmi oracle-java8_sshd
docker rmi python
docker rmi nodejs
docker rmi mysql
docker rmi mongodb
docker rmi apache
docker rmi tomcat
docker rmi hadoop_pseudo-distributed
docker rmi wei1234c/hadoop_pseudo-distributed_armv7
docker rmi hadoop_distributed
